language: groovy
sudo: false

matrix:
  include:
  - os: linux
    jdk: oraclejdk7
  - os: osx
    osx_image: xcode7.3

cache:
  directories:
  - $HOME/.gradle

before_install:
- ./gradlew installDeps
